config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  '/teryt/:teryt/file_pdf', to: 'teryt#file_pdf'
  get  '/teryt/:teryt/file_xlsx', to: 'teryt#file_xlsx'

  get '/api_teryt/provinces',          to: 'api_teryt#provinces'
  get '/api_teryt/province_districts', to: 'api_teryt#province_districts'
  get '/api_teryt/district_communes',  to: 'api_teryt#district_communes'

  post '/areas/find_or_create', to: 'areas#find_or_create'
  get  '/areas/info', to: 'areas#info'
  get  '/areas/declaration', to: 'areas#declaration'

  # resources :areas, except: [:show, :create]
  resources :areas, only: [:index]

  root 'areas#index'
end

app/views/layouts/_errors.html.erb
<% content_for :form_errors do %>
  <div id="error_explanation" class="panel panel-danger">
    <div class="panel-heading">
      <div class="panel-title">
        <span class="glyphicon glyphicon-flash">&nbsp;Uwaga!</span>

        <button type="button" class="close" data-target="#error_explanation" data-dismiss="alert"> <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>

      </div> 
    </div>

    <div class="panel-body">
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><h5><%= msg %></h5></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>
 

app/views/layouts/_eu.html.erb
<div class="container">
  <div class="row">
    <hr>
    <div class='col-sm-3'>
    </div> 
    <div class='col-sm-6'>
      <span><%= image_tag( 'eu.png', alt: 'EU Logo', class: "img img-responsive center-block" ) %></span>
    </div>  <!-- /col-sm-10 -->
    <div class='col-sm-3'>
    </div>
  </div>  <!-- /row -->
  <br>
</div>  <!-- /container -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class='col-sm-6'>
      <h4><%= t('.brand') %></h4>
      <h4><%= t('.brand_address_1') %></h4>
      <h4><%= t('.brand_address_2') %></h4>
      <br>
      <h5><%= t('.brand_note') %></h5>
      <hr class="visible-xs">
    </div>

    <div class='col-sm-3'>
      <h5><%= t('.contact') %></h5>
        <ul><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;<%= mail_to t('.contact_mail') %></ul>
        <ul><span class="fa fa-phone"></span>&nbsp;&nbsp;T:&nbsp;<%= link_to t('.contact_phone'), "tel:#{t('.contact_phone')}" %></ul>
        <ul><span class="fa fa-fax"></span>&nbsp;&nbsp;F:&nbsp;<%= link_to t('.contact_fax'), "tel:#{t('.contact_fax')}" %></ul>
      <hr class="visible-xs">
    </div>

    <div class="col-sm-3">
      <h5><%= t('.links') %></h5>
        <ul><span class="fa fa-info-circle"></span>&nbsp;&nbsp;
          <%= link_to areas_declaration_path do %>
            <%= t("areas.declaration.navbar") %>
          <% end %>
        </ul>
        <ul><span class="fa fa-globe"></span>&nbsp;&nbsp;<%= link_to('UKE', 'http://uke.gov.pl', target: "_blank") %></ul>
        <ul><span class="fa fa-globe"></span>&nbsp;&nbsp;<%= link_to('Facebook', 'https://web.facebook.com/UrzadKomunikacjiElektronicznej', target: "_blank") %></ul>
        <ul><span class="fa fa-globe"></span>&nbsp;&nbsp;<%= link_to('Twitter', 'https://twitter.com/uke2uke', target: "_blank") %></ul>
      <hr class="visible-xs">

      <h6 class="pull-right">&copy; 2018 UKE</h6>

    </div>
  </div>  <!-- /row -->

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to "MAP-BOOKS", root_path, id: "logo" %>
      <%#= link_to( image_tag( t('logo_file'), alt: 'Logo', :class => "img img-responsive" ), t('logo_link') ) %>

      <div class="navbar-brand navbar-brand-logo">
        <%= link_to( image_tag( t('logo_file'), alt: 'app logo', :class => "img img-responsive" ), root_path ) %>
      </div>

    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <nav>

        <ul class="nav navbar-nav navbar-left">
        </ul>

        <ul class="nav navbar-nav navbar-right">
              <li><%= link_to areas_info_path do %>
                <span class="fa fa-info-circle"></span>&nbsp;<%=t "areas.info.navbar" %>
                <% end %>
              </li>
              <li><%= link_to areas_path do %>
                <span class="fa fa-atlas"></span>&nbsp;<%=t "areas.index.navbar" %>
                <% end %>
              </li>
        </ul>

      </nav>
    </div>

    <hr class="hr-without-all-margin">

  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= flash_class_name(name) %>" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
      </button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8">
    <meta lang="pl">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UKE MapBook" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "UKE MapBook" %>">

    <!-- IE Compatible -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'shortcut icon', :type => "image/x-icon" %>

    <%= yield(:javascript) %> 

    <%= piwik_tracking_tag %>
  </head>

  <body>
    <div class="content">
      <%= render 'layouts/header', cached: true %>
      <main>
        <%= render 'layouts/messages' %>
        <%= yield(:form_errors) %>       
        <%= yield %>
      </main>
    </div>
    <%= render 'layouts/eu', cached: true %>
    <%= render 'layouts/footer', cached: true %>
  </body>
</html>